import { Migration } from '@mikro-orm/migrations';

/**
 * PRM WIC ingestion — base tables (Spec #4 — wic-ingestion).
 *
 * Auto-generated by `yarn mercato db generate` after adding `WICContribution`,
 * `WICImportAuditLog`, and `ServiceIdempotencyKey` to `data/entities.ts`. The
 * companion migration `Migration20260506183816_prm_wic_indexes.ts` ships the
 * partial-unique index + CHECK constraints + FK constraints that aren't
 * derivable from MikroORM decorators alone (matches the existing PRM pattern
 * — see `Migration20260505100000_prm_indexes.ts`).
 *
 * **Additive only** — no DROP / ALTER COLUMN.
 */
export class Migration20260506183815_prm_wic extends Migration {

  override async up(): Promise<void> {
    this.addSql(`create table "prm_service_idempotency_key" ("endpoint" text not null, "idempotency_key" uuid not null, "tenant_id" uuid not null, "organization_id" uuid not null, "payload_hash" text not null, "response_hash" text not null, "response_status" int not null, "response_body" jsonb not null, "created_at" timestamptz not null, constraint "prm_service_idempotency_key_pkey" primary key ("endpoint", "idempotency_key"));`);
    this.addSql(`create index "prm_service_idempotency_key_tenant_id_index" on "prm_service_idempotency_key" ("tenant_id");`);
    this.addSql(`create index "prm_service_idempotency_key_organization_id_index" on "prm_service_idempotency_key" ("organization_id");`);

    this.addSql(`create table "prm_wic_contributions" ("id" uuid not null default gen_random_uuid(), "tenant_id" uuid not null, "organization_id" uuid not null, "agency_id" uuid not null, "agency_member_id" uuid not null, "github_profile" text not null, "contribution_month" date not null, "wic_level" text null, "wic_score" numeric(12,4) not null, "contribution_count" int not null default 0, "bounty_bonus" numeric(12,4) not null default '0', "why_bonus" text null, "what_included" text null, "what_excluded" text null, "script_version" text not null, "import_batch_id" uuid not null, "row_index" int not null, "computed_at" timestamptz not null, "imported_at" timestamptz not null, "superseded_by_id" uuid null, "archived_at" timestamptz null, "created_at" timestamptz not null, "updated_at" timestamptz not null, constraint "prm_wic_contributions_pkey" primary key ("id"));`);
    this.addSql(`create index "prm_wic_contributions_tenant_id_index" on "prm_wic_contributions" ("tenant_id");`);
    this.addSql(`create index "prm_wic_contributions_organization_id_index" on "prm_wic_contributions" ("organization_id");`);
    this.addSql(`create index "prm_wic_contributions_agency_id_index" on "prm_wic_contributions" ("agency_id");`);
    this.addSql(`create index "prm_wic_contributions_agency_member_id_index" on "prm_wic_contributions" ("agency_member_id");`);
    this.addSql(`create index "prm_wic_contributions_contribution_month_index" on "prm_wic_contributions" ("contribution_month");`);
    this.addSql(`create index "prm_wic_contributions_import_batch_id_index" on "prm_wic_contributions" ("import_batch_id");`);
    this.addSql(`create index "prm_wic_contributions_superseded_by_id_index" on "prm_wic_contributions" ("superseded_by_id");`);
    this.addSql(`alter table "prm_wic_contributions" add constraint "prm_wic_contributions_batch_row_uniq" unique ("import_batch_id", "row_index");`);

    this.addSql(`create table "prm_wic_import_audit_log" ("id" uuid not null default gen_random_uuid(), "tenant_id" uuid not null, "organization_id" uuid not null, "import_batch_id" uuid not null, "row_index" int not null, "raw_payload" jsonb not null, "rejection_reason" text not null, "rejection_detail" text null, "resolved_agency_id" uuid null, "script_version" text not null, "month" text not null, "created_at" timestamptz not null, "resolved_at" timestamptz null, "resolved_by_user_id" uuid null, "resolution_action" text null, "resolution_note" text null, constraint "prm_wic_import_audit_log_pkey" primary key ("id"));`);
    this.addSql(`create index "prm_wic_import_audit_log_tenant_id_index" on "prm_wic_import_audit_log" ("tenant_id");`);
    this.addSql(`create index "prm_wic_import_audit_log_organization_id_index" on "prm_wic_import_audit_log" ("organization_id");`);
    this.addSql(`create index "prm_wic_import_audit_log_import_batch_id_index" on "prm_wic_import_audit_log" ("import_batch_id");`);
    this.addSql(`create index "prm_wic_import_audit_log_rejection_reason_index" on "prm_wic_import_audit_log" ("rejection_reason");`);
    this.addSql(`create index "prm_wic_import_audit_log_resolved_agency_id_index" on "prm_wic_import_audit_log" ("resolved_agency_id");`);
    this.addSql(`create index "prm_wic_import_audit_log_resolved_at_index" on "prm_wic_import_audit_log" ("resolved_at");`);
    this.addSql(`alter table "prm_wic_import_audit_log" add constraint "prm_wic_import_audit_log_batch_row_uniq" unique ("import_batch_id", "row_index");`);
  }

  override async down(): Promise<void> {
    this.addSql(`drop table if exists "prm_wic_import_audit_log";`);
    this.addSql(`drop table if exists "prm_wic_contributions";`);
    this.addSql(`drop table if exists "prm_service_idempotency_key";`);
  }

}
